version: "3.3"
services:
  mysql-dev1:
      build: .
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: test_db
      # command:
      #   - /bin/bash
      #   - -c
      #   - |
      #     mysql -uroot -ppassword \
      #     -e "CREATE USER 'inno@%' IDENIFIED BY 'inno';" \
      #     -e "GRANT ALL privileges ON *.* TO 'inno'@'%' with grant option;" \
      #     -e "reset master;"
      volumes:
      - ./db-data1:/var/lib/mysql
      ports:
      - "3306:3306"
  
  mysql-dev2:
      build: .
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: test_db
      # command:
      #   - /bin/bash
      #   - -c
      #   - |
      #     mysql -uroot -ppassword \
      #     -e "CREATE USER 'inno@%' IDENIFIED BY 'inno';" \
      #     -e "GRANT ALL privileges ON *.* TO 'inno'@'%' with grant option;" \
      #     -e "reset master;"
      ports:
      - "3307:3306"
      volumes:
      - ./db-data2:/var/lib/mysql
  
  mysql-dev3:
      build: .
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: test_db
      # command:
      #   - /bin/bash
      #   - -c
      #   - |
      #     mysql -uroot -ppassword \
      #     -e "CREATE USER 'inno@%' IDENIFIED BY 'inno';" \
      #     -e "GRANT ALL privileges ON *.* TO 'inno'@'%' with grant option;" \
      #     -e "reset master;"
      ports:
      - "3308:3306"
      volumes:
      - ./db-data3:/var/lib/mysql

volumes:
  db-data1:
    driver: local
  db-data2:
    driver: local
  db-data3:
    driver: local